apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld-svc
  namespace: springboot-helloworld
spec:
  selector:
    app: springboot-helloworld-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer